[package]
name = "tsk"
version = "0.4.0"
authors = ["matthew seyer <https://github.com/forensicmatt/libtsk-rs>"]
edition = "2018"

[dependencies]
log = "=0.4"
clap = "=2"

[build-dependencies]
glob = "=0.3.0"
bindgen = "=0.68.1"

[target.'cfg(windows)'.build-dependencies.winreg]
version = "=0.7"
